---
sidebar_position: 1
title: "Templates"
description: Quick Start with Templates!
sidebar_label: Templates
---

# Auth Templates

Zeromagic allows to personalize user communication by offering customizable templates for one-time codes (OTPs), password resets, and email confirmations. These templates offer flexibility by including **built-in placeholders** that can be dynamically replaced with actual values from your backend system. 

## Template Configuration

Within your Zeromagic project console, navigate to the `Configuration` section to managing templates.

### Template 1: SMS OTP

This template is used to send a one-time password (OTP) via SMS for user verification. The keyword `OTP` will be replaced with the actual OTP code generated by the system.

```jsx title="Sample Template"
Your one-time code to access your Zeromagic account is: {{OTP}}. This code is valid for 2 minutes. Do not share this code with anyone.
```

| Variable | Description                               |
| -------- | ----------------------------------------- |
| OTP      | Replaced with OTP code generated by sytem |

### Template 2: EMAIL OTP

Similar to the SMS OTP template, this template is used to send a one-time password (OTP) via email for user verification. The keyword `OTP` will be replaced with the actual OTP code generated by the system.

```jsx title="Sample Template"
We have sent you a one-time password to access your Zeromagic account. Use this code to complete your login:
OTP: {{OTP}}
This code is valid for 10 minutes. Please do not share this code with anyone.
```

| Variable | Description                               |
| -------- | ----------------------------------------- |
| OTP      | Replaced with OTP code generated by sytem |

### Template 3: EMAIL VERIFICATION

This template is used to send an email verification link to users for confirming their email address. The link will direct users to a verification page where they can confirm their email address. The keyword `VERIFY_URL` will be replaced with the actual verification link generated by the system.

```jsx title="Sample Template"
Thank you for creating an account with Zeromagic! To complete your registration and access all our features, please verify your email address by clicking the link below:
{{VERIFY_URL}}
If you didnt create an account with Zeromagic, please disregard this email.
```

| Variable   | Description                                        |
| ---------- | -------------------------------------------------- |
| VERIFY_URL | Replaced with verification link generated by sytem |

### Template 4: PASSWORD RESET

This template is used to send a password reset link to users who have requested to reset their password. The link will direct users to a password reset page where they can create a new password. The keyword `VERIFY_URL` will be replaced with the actual password reset link generated by the system.

```jsx title="Sample Template"
We received a request to reset your password for your Zeromagic account.
Click the link below to set a new password:
{{VERIFY_URL}}
This link is valid for 2 hours. If you didn't request a password reset, please contact  Zeromagic support immediately.
```

| Variable   | Description                                          |
| ---------- | ---------------------------------------------------- |
| VERIFY_URL | Replaced with password reset link generated by sytem |
